import { afterAll, beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("next/cache", () => ({ revalidatePath: vi.fn() }));

import { eq } from "drizzle-orm";
import { db, getPool, schema } from "../src/db";
import { generateRecurringBills, getBooksSnapshot, monthKey } from "../src/lib/books";
import { newId } from "../src/lib/id";

const TZ = "America/Toronto";
/** Mid-month, mid-afternoon local — safely inside August in every timezone. */
const AUGUST = new Date("2026-08-15T18:00:00Z");

let rentCategoryId: string;
let hydroCategoryId: string;

beforeEach(async () => {
  await db().execute(
    `TRUNCATE expenses, recurring_bills, expense_categories, invoice_line_items, invoice_jobs,
     payments, invoices, vehicles, customers, audit_log, staff_users, invoice_counters
     RESTART IDENTITY CASCADE` as never,
  );
  rentCategoryId = newId("exc");
  hydroCategoryId = newId("exc");
  await db().insert(schema.expenseCategories).values([
    { id: rentCategoryId, name: "Rent", sort: 0 },
    { id: hydroCategoryId, name: "Hydro", sort: 1 },
  ]);
});

afterAll(async () => {
  await getPool().end();
});

async function addBill(overrides: Partial<typeof schema.recurringBills.$inferInsert> = {}) {
  const id = newId("rbl");
  await db().insert(schema.recurringBills).values({
    id,
    name: "Shop Rent",
    categoryId: rentCategoryId,
    amountCents: 250_000,
    startMonth: "2026-01",
    active: true,
    ...overrides,
  });
  return id;
}

describe("generateRecurringBills", () => {
  it("creates one expense per active bill for the month", async () => {
    await addBill();
    await addBill({ name: "Hydro", categoryId: hydroCategoryId, amountCents: 22_000 });

    expect(await generateRecurringBills(AUGUST)).toBe(2);

    const rows = await db().select().from(schema.expenses);
    expect(rows).toHaveLength(2);
    expect(rows.every((row) => row.autoGenerated)).toBe(true);
    expect(rows.every((row) => row.periodMonth === "2026-08")).toBe(true);
    // Unconfirmed and claiming no input credit until the real bill arrives.
    expect(rows.every((row) => row.confirmedAt === null)).toBe(true);
    expect(rows.every((row) => row.taxPaidCents === 0)).toBe(true);
  });

  it("is a no-op when run again in the same month", async () => {
    await addBill();
    expect(await generateRecurringBills(AUGUST)).toBe(1);
    expect(await generateRecurringBills(AUGUST)).toBe(0);
    expect(await generateRecurringBills(AUGUST)).toBe(0);
    expect(await db().select().from(schema.expenses)).toHaveLength(1);
  });

  it("survives two schedulers racing the same month", async () => {
    await addBill();
    // The unique index, not application logic, is what makes this safe.
    const [first, second] = await Promise.all([
      generateRecurringBills(AUGUST),
      generateRecurringBills(AUGUST),
    ]);
    expect(first + second).toBe(1);
    expect(await db().select().from(schema.expenses)).toHaveLength(1);
  });

  it("generates again in the following month", async () => {
    await addBill();
    await generateRecurringBills(AUGUST);
    await generateRecurringBills(new Date("2026-09-15T18:00:00Z"));

    const rows = await db().select().from(schema.expenses);
    expect(rows.map((row) => row.periodMonth).sort()).toEqual(["2026-08", "2026-09"]);
  });

  it("skips inactive bills and bills outside their window", async () => {
    await addBill({ name: "Switched off", active: false });
    await addBill({ name: "Not started", startMonth: "2026-09" });
    await addBill({ name: "Finished", startMonth: "2026-01", endMonth: "2026-07" });

    expect(await generateRecurringBills(AUGUST)).toBe(0);
    expect(await db().select().from(schema.expenses)).toHaveLength(0);
  });

  it("keeps a corrected amount when the next month generates", async () => {
    const billId = await addBill({ name: "Hydro", categoryId: hydroCategoryId, amountCents: 22_000 });
    await generateRecurringBills(AUGUST);

    // The owner corrects August to the real figure off the bill.
    await db()
      .update(schema.expenses)
      .set({ amountCents: 27_450, taxPaidCents: 3_158, confirmedAt: new Date() })
      .where(eq(schema.expenses.recurringBillId, billId));

    await generateRecurringBills(new Date("2026-09-15T18:00:00Z"));
    const rows = await db().select().from(schema.expenses);
    const august = rows.find((row) => row.periodMonth === "2026-08");
    const september = rows.find((row) => row.periodMonth === "2026-09");

    expect(august?.amountCents).toBe(27_450);
    expect(september?.amountCents).toBe(22_000);
  });

  it("files a generated bill under the month it belongs to, not UTC's", async () => {
    await addBill();
    // 31 Aug 21:00 EDT is 1 Sep 01:00 UTC. Using UTC here would file the bill
    // into September and leave August without its rent.
    const lateAugust = new Date("2026-09-01T01:00:00Z");
    expect(monthKey(lateAugust, TZ)).toBe("2026-08");
    await generateRecurringBills(lateAugust);

    const [row] = await db().select().from(schema.expenses);
    expect(row.periodMonth).toBe("2026-08");
  });
});

describe("getBooksSnapshot", () => {
  it("subtracts expenses from invoiced sales and nets the tax position", async () => {
    const customerId = newId("cus");
    await db().insert(schema.customers).values({
      id: customerId,
      firstName: "Marcus",
      lastName: "Bell",
      preferredContact: "phone",
    });
    await db().insert(schema.invoices).values({
      id: newId("inv"),
      number: 3001,
      customerId,
      status: "paid",
      subtotalCents: 100_000,
      discountCents: 10_000,
      taxRateBp: 1300,
      taxLabel: "HST",
      taxCents: 11_700,
      totalCents: 101_700,
      invoiceDate: new Date("2026-08-10T16:00:00Z"),
    });
    await db().insert(schema.expenses).values({
      id: newId("exp"),
      expenseDate: new Date("2026-08-12T16:00:00Z"),
      categoryId: rentCategoryId,
      amountCents: 250_000,
      taxPaidCents: 0,
    });
    await db().insert(schema.expenses).values({
      id: newId("exp"),
      expenseDate: new Date("2026-08-12T16:00:00Z"),
      categoryId: hydroCategoryId,
      amountCents: 11_300,
      taxPaidCents: 1_300,
    });

    const books = await getBooksSnapshot("month", 2026, 8);
    expect(books.pnl.netSalesCents).toBe(90_000);
    expect(books.pnl.expenses.totalCents).toBe(261_300);
    expect(books.pnl.netProfitCents).toBe(90_000 - 261_300);
    expect(books.tax.collectedCents).toBe(11_700);
    expect(books.tax.inputCreditCents).toBe(1_300);
    expect(books.tax.netOwingCents).toBe(10_400);
    // Nothing existed a year earlier, so there is no comparison to draw.
    expect(books.priorYear).toBeNull();
  });

  it("excludes an expense that falls in a neighbouring month", async () => {
    await db().insert(schema.expenses).values({
      id: newId("exp"),
      // 1 Sep 00:30 EDT — September's, even though it is still August in UTC.
      expenseDate: new Date("2026-09-01T04:30:00Z"),
      categoryId: rentCategoryId,
      amountCents: 5_000,
      taxPaidCents: 0,
    });

    expect((await getBooksSnapshot("month", 2026, 8)).pnl.expenses.totalCents).toBe(0);
    expect((await getBooksSnapshot("month", 2026, 9)).pnl.expenses.totalCents).toBe(5_000);
  });
});
