"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { PeriodNav } from "@/components/period-nav";
import { formatCents } from "@/lib/money";
import {
  EXPENSE_PAYMENT_METHODS,
  EXPENSE_PAYMENT_METHOD_LABELS,
  type ExpensePaymentMethod,
} from "@/lib/types";
import {
  confirmBillsAction,
  createExpenseAction,
  deleteExpenseAction,
  updateExpenseAction,
} from "./actions";

type Category = { id: string; name: string; isPayroll: boolean; active: boolean };
type StaffOption = { id: string; name: string };
type CategoryTotal = { categoryId: string; name: string; amountCents: number; count: number };

type ExpenseRow = {
  id: string;
  expenseDate: string;
  categoryId: string;
  categoryName: string;
  paidTo: string | null;
  staffName: string | null;
  description: string | null;
  amountCents: number;
  taxPaidCents: number;
  paidBy: string;
  reference: string | null;
  autoGenerated: boolean;
  confirmedAt: string | null;
  notes: string | null;
};

type PeriodInfo = { kind: "month" | "quarter" | "year"; year: number; index: number; label: string };

const input =
  "w-full rounded-lg border border-ink-600 bg-ink-950 px-3 py-2 text-sm text-white placeholder:text-ink-500 focus:border-accent-500 focus:outline-none";
const label = "block text-xs font-medium text-ink-400";
const card = "rounded-2xl border border-ink-700 bg-ink-900/50 p-5";

function toCents(dollars: string): number {
  const value = Number(dollars);
  return Number.isFinite(value) ? Math.round(value * 100) : 0;
}
const toDollars = (cents: number) => (cents / 100).toFixed(2);

/** Blank form state, with today's date and the first selectable category. */
function emptyForm(today: string, categories: Category[]) {
  return {
    expenseDate: today,
    categoryId: categories.find((category) => category.active)?.id ?? "",
    paidTo: "",
    staffUserId: "",
    description: "",
    amount: "",
    taxPaid: "",
    paidBy: "other" as ExpensePaymentMethod,
    reference: "",
    notes: "",
  };
}
type FormState = ReturnType<typeof emptyForm>;

export function ExpenseManager({
  period,
  today,
  currency,
  taxRateBp,
  taxLabel,
  categories,
  staff,
  summary,
  expenses,
}: {
  period: PeriodInfo;
  today: string;
  currency: string;
  taxRateBp: number;
  taxLabel: string;
  timezone: string;
  categories: Category[];
  staff: StaffOption[];
  summary: {
    totalCents: number;
    inputTaxCreditCents: number;
    count: number;
    byCategory: CategoryTotal[];
  };
  expenses: ExpenseRow[];
}) {
  const router = useRouter();
  const money = (cents: number) => formatCents(cents, currency);
  const unconfirmed = expenses.filter((row) => row.autoGenerated && !row.confirmedAt);

  const largest = Math.max(1, ...summary.byCategory.map((entry) => entry.amountCents));

  return (
    <div className="max-w-6xl">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-white">Expenses</h1>
          <p className="mt-1 text-sm text-ink-400">
            Everything the business pays out. Feeds net profit and your {taxLabel} input credits in
            Reports.
          </p>
        </div>
      </div>

      <div className="mt-6 flex flex-wrap items-center justify-between gap-3">
        <PeriodNav period={period} basePath="/admin/expenses" />
        <a
          href={`/api/reports/export?kind=expenses&kindPeriod=${period.kind}&y=${period.year}&i=${period.index}`}
          className="rounded-lg border border-ink-600 px-3 py-2 text-xs font-medium text-ink-200 hover:bg-ink-800"
        >
          Export CSV
        </a>
      </div>

      {/* Headline numbers */}
      <div className="mt-4 grid gap-4 sm:grid-cols-3">
        <div className={card}>
          <p className="text-sm text-ink-400">Total spent</p>
          <p className="mt-1 text-3xl font-bold text-white">{money(summary.totalCents)}</p>
          <p className="mt-2 text-xs text-ink-400">{period.label}</p>
        </div>
        <div className={card}>
          <p className="text-sm text-ink-400">{taxLabel} paid on purchases</p>
          <p className="mt-1 text-3xl font-bold text-white">{money(summary.inputTaxCreditCents)}</p>
          <p className="mt-2 text-xs text-ink-400">Claimed back as input credits</p>
        </div>
        <div className={card}>
          <p className="text-sm text-ink-400">Payments recorded</p>
          <p className="mt-1 text-3xl font-bold text-white">{summary.count}</p>
          <p className="mt-2 text-xs text-ink-400">
            {unconfirmed.length > 0 ? `${unconfirmed.length} still to confirm` : "All confirmed"}
          </p>
        </div>
      </div>

      {unconfirmed.length > 0 && (
        <BillsToConfirm rows={unconfirmed} money={money} onDone={() => router.refresh()} />
      )}

      <AddExpense
        today={today}
        categories={categories}
        staff={staff}
        taxRateBp={taxRateBp}
        taxLabel={taxLabel}
        currency={currency}
      />

      {/* Where the money went */}
      {summary.byCategory.length > 0 && (
        <section className="mt-8">
          <h2 className="text-sm font-semibold uppercase tracking-wider text-ink-400">
            Where it went
          </h2>
          <div className="mt-3 space-y-2">
            {summary.byCategory.map((entry) => (
              <div key={entry.categoryId} className="flex items-center gap-3">
                <span className="w-40 shrink-0 truncate text-sm text-ink-200">{entry.name}</span>
                <div className="h-2 flex-1 overflow-hidden rounded-full bg-ink-800">
                  <div
                    className="h-full rounded-full bg-accent-400"
                    style={{ width: `${Math.max(2, (entry.amountCents / largest) * 100)}%` }}
                  />
                </div>
                <span className="w-24 shrink-0 text-right text-sm font-medium text-white">
                  {money(entry.amountCents)}
                </span>
              </div>
            ))}
          </div>
        </section>
      )}

      {/* Ledger */}
      <section className="mt-8">
        <h2 className="text-sm font-semibold uppercase tracking-wider text-ink-400">
          Payments ({expenses.length})
        </h2>
        {expenses.length === 0 ? (
          <p className="mt-3 rounded-xl border border-dashed border-ink-700 p-8 text-center text-sm text-ink-400">
            Nothing recorded for {period.label} yet. Add your first expense above.
          </p>
        ) : (
          <div className="mt-3 space-y-2">
            {expenses.map((row) => (
              <ExpenseListRow
                key={row.id}
                row={row}
                categories={categories}
                staff={staff}
                currency={currency}
                taxRateBp={taxRateBp}
                taxLabel={taxLabel}
              />
            ))}
          </div>
        )}
      </section>
    </div>
  );
}

/** Generated bills the owner has not ticked off yet. */
function BillsToConfirm({
  rows,
  money,
  onDone,
}: {
  rows: ExpenseRow[];
  money: (cents: number) => string;
  onDone: () => void;
}) {
  const [busy, setBusy] = useState(false);

  async function confirmAll() {
    setBusy(true);
    await confirmBillsAction({ expenseIds: rows.map((row) => row.id) });
    setBusy(false);
    onDone();
  }

  return (
    <section className="mt-6 rounded-2xl border border-accent-500/40 bg-accent-400/5 p-5">
      <h2 className="text-sm font-semibold text-accent-300">
        {rows.length} monthly {rows.length === 1 ? "bill" : "bills"} to confirm
      </h2>
      <p className="mt-1 text-xs text-ink-300">
        These were created automatically from your recurring bills. Check the amount — open one to
        correct it (hydro varies) or delete it if it did not arrive this month.
      </p>
      <ul className="mt-3 space-y-1 text-sm text-ink-200">
        {rows.map((row) => (
          <li key={row.id} className="flex justify-between gap-4">
            <span className="truncate">{row.description ?? row.categoryName}</span>
            <span className="shrink-0 font-medium text-white">{money(row.amountCents)}</span>
          </li>
        ))}
      </ul>
      <button
        type="button"
        onClick={() => void confirmAll()}
        disabled={busy}
        className="mt-4 rounded-lg bg-accent-400 px-4 py-2 text-sm font-semibold text-ink-950 hover:bg-accent-300 disabled:opacity-40"
      >
        {busy ? "Confirming…" : "These are all correct"}
      </button>
    </section>
  );
}

/** Shared amount + tax pair, with the HST back-out button. */
function AmountFields({
  amount,
  taxPaid,
  onAmount,
  onTaxPaid,
  taxRateBp,
  taxLabel,
}: {
  amount: string;
  taxPaid: string;
  onAmount: (value: string) => void;
  onTaxPaid: (value: string) => void;
  taxRateBp: number;
  taxLabel: string;
}) {
  // Mirrors taxIncludedInCents in src/lib/books.ts: the tax inside a
  // tax-inclusive total, not the tax added on top of it.
  const included = useMemo(() => {
    const cents = toCents(amount);
    if (cents <= 0 || taxRateBp <= 0) return 0;
    return Math.round((cents * taxRateBp) / (10_000 + taxRateBp));
  }, [amount, taxRateBp]);

  return (
    <>
      <label className={label}>
        Amount paid
        <input
          type="number"
          step="0.01"
          min="0"
          inputMode="decimal"
          placeholder="0.00"
          value={amount}
          onChange={(event) => onAmount(event.target.value)}
          className={`${input} mt-1`}
        />
      </label>
      <label className={label}>
        {taxLabel} within that amount
        <input
          type="number"
          step="0.01"
          min="0"
          inputMode="decimal"
          placeholder="0.00"
          value={taxPaid}
          onChange={(event) => onTaxPaid(event.target.value)}
          className={`${input} mt-1`}
        />
        {included > 0 && (
          <button
            type="button"
            onClick={() => onTaxPaid(toDollars(included))}
            className="mt-1.5 text-xs text-accent-300 underline underline-offset-2 hover:text-accent-200"
          >
            Receipt includes {taxLabel}? Use {(included / 100).toFixed(2)}
          </button>
        )}
      </label>
    </>
  );
}

function AddExpense({
  today,
  categories,
  staff,
  taxRateBp,
  taxLabel,
  currency,
}: {
  today: string;
  categories: Category[];
  staff: StaffOption[];
  taxRateBp: number;
  taxLabel: string;
  currency: string;
}) {
  const router = useRouter();
  const [form, setForm] = useState<FormState>(() => emptyForm(today, categories));
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [saved, setSaved] = useState(false);

  const category = categories.find((item) => item.id === form.categoryId);
  const set = <K extends keyof FormState>(key: K, value: FormState[K]) =>
    setForm((current) => ({ ...current, [key]: value }));

  async function save() {
    setBusy(true);
    setError(null);
    setSaved(false);
    const result = await createExpenseAction({
      expenseDate: form.expenseDate,
      categoryId: form.categoryId,
      paidTo: form.paidTo,
      staffUserId: form.staffUserId || null,
      description: form.description,
      amountCents: toCents(form.amount),
      taxPaidCents: toCents(form.taxPaid),
      paidBy: form.paidBy,
      reference: form.reference,
      notes: form.notes,
    });
    setBusy(false);
    if (!result.ok) {
      setError(result.error);
      return;
    }
    // Keep the date and category — expenses are entered in batches from a pile
    // of receipts, and re-picking the same category every time is the friction
    // that sends people back to the spreadsheet.
    setForm((current) => ({
      ...emptyForm(today, categories),
      expenseDate: current.expenseDate,
      categoryId: current.categoryId,
      paidBy: current.paidBy,
    }));
    setSaved(true);
    router.refresh();
  }

  return (
    <section className={`mt-8 ${card}`}>
      <h2 className="text-sm font-semibold uppercase tracking-wider text-ink-400">Add an expense</h2>
      <div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        <label className={label}>
          Date
          <input
            type="date"
            value={form.expenseDate}
            onChange={(event) => set("expenseDate", event.target.value)}
            className={`${input} mt-1`}
          />
        </label>
        <label className={label}>
          Category
          <select
            value={form.categoryId}
            onChange={(event) => set("categoryId", event.target.value)}
            className={`${input} mt-1`}
          >
            {categories
              .filter((item) => item.active || item.id === form.categoryId)
              .map((item) => (
                <option key={item.id} value={item.id}>
                  {item.name}
                  {item.active ? "" : " (inactive)"}
                </option>
              ))}
          </select>
        </label>
        {category?.isPayroll ? (
          <label className={label}>
            Who was paid?
            <select
              value={form.staffUserId}
              onChange={(event) => set("staffUserId", event.target.value)}
              className={`${input} mt-1`}
            >
              <option value="">Select a staff member…</option>
              {staff.map((member) => (
                <option key={member.id} value={member.id}>
                  {member.name}
                </option>
              ))}
            </select>
          </label>
        ) : (
          <label className={label}>
            Paid to
            <input
              value={form.paidTo}
              onChange={(event) => set("paidTo", event.target.value)}
              placeholder="Supplier or vendor"
              className={`${input} mt-1`}
            />
          </label>
        )}
        <AmountFields
          amount={form.amount}
          taxPaid={form.taxPaid}
          onAmount={(value) => set("amount", value)}
          onTaxPaid={(value) => set("taxPaid", value)}
          taxRateBp={taxRateBp}
          taxLabel={taxLabel}
        />
        <label className={label}>
          Paid by
          <select
            value={form.paidBy}
            onChange={(event) => set("paidBy", event.target.value as ExpensePaymentMethod)}
            className={`${input} mt-1`}
          >
            {EXPENSE_PAYMENT_METHODS.map((method) => (
              <option key={method} value={method}>
                {EXPENSE_PAYMENT_METHOD_LABELS[method]}
              </option>
            ))}
          </select>
        </label>
        <label className={label}>
          What was it for
          <input
            value={form.description}
            onChange={(event) => set("description", event.target.value)}
            placeholder="Optional"
            className={`${input} mt-1`}
          />
        </label>
        <label className={label}>
          Invoice / cheque number
          <input
            value={form.reference}
            onChange={(event) => set("reference", event.target.value)}
            placeholder="Optional"
            className={`${input} mt-1`}
          />
        </label>
      </div>

      {error && <p className="mt-3 text-sm text-red-400">{error}</p>}
      {saved && <p className="mt-3 text-sm text-emerald-300">Expense saved.</p>}

      <div className="mt-4 flex flex-wrap items-center gap-3">
        <button
          type="button"
          onClick={() => void save()}
          disabled={busy}
          className="rounded-lg bg-accent-400 px-5 py-2.5 text-sm font-semibold text-ink-950 hover:bg-accent-300 disabled:opacity-40"
        >
          {busy ? "Saving…" : "Save expense"}
        </button>
        {toCents(form.amount) > 0 && (
          <span className="text-sm text-ink-400">
            Recording {formatCents(toCents(form.amount), currency)}
          </span>
        )}
      </div>
    </section>
  );
}

function ExpenseListRow({
  row,
  categories,
  staff,
  currency,
  taxRateBp,
  taxLabel,
}: {
  row: ExpenseRow;
  categories: Category[];
  staff: StaffOption[];
  currency: string;
  taxRateBp: number;
  taxLabel: string;
}) {
  const router = useRouter();
  const [open, setOpen] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [confirmingDelete, setConfirmingDelete] = useState(false);
  const [form, setForm] = useState({
    expenseDate: row.expenseDate.slice(0, 10),
    categoryId: row.categoryId,
    paidTo: row.paidTo ?? "",
    staffUserId: staff.find((member) => member.name === row.staffName)?.id ?? "",
    description: row.description ?? "",
    amount: toDollars(row.amountCents),
    taxPaid: toDollars(row.taxPaidCents),
    paidBy: row.paidBy as ExpensePaymentMethod,
    reference: row.reference ?? "",
    notes: row.notes ?? "",
  });

  const category = categories.find((item) => item.id === form.categoryId);
  const set = <K extends keyof typeof form>(key: K, value: (typeof form)[K]) =>
    setForm((current) => ({ ...current, [key]: value }));

  async function save() {
    setBusy(true);
    setError(null);
    const result = await updateExpenseAction({
      expenseId: row.id,
      expenseDate: form.expenseDate,
      categoryId: form.categoryId,
      paidTo: form.paidTo,
      staffUserId: form.staffUserId || null,
      description: form.description,
      amountCents: toCents(form.amount),
      taxPaidCents: toCents(form.taxPaid),
      paidBy: form.paidBy,
      reference: form.reference,
      notes: form.notes,
    });
    setBusy(false);
    if (!result.ok) return setError(result.error);
    setOpen(false);
    router.refresh();
  }

  async function remove() {
    setBusy(true);
    setError(null);
    const result = await deleteExpenseAction({ expenseId: row.id });
    setBusy(false);
    if (!result.ok) return setError(result.error);
    router.refresh();
  }

  const day = new Date(row.expenseDate).toLocaleDateString("en-CA", {
    month: "short",
    day: "numeric",
  });

  return (
    <article
      className={`rounded-xl border transition-colors ${
        row.autoGenerated && !row.confirmedAt
          ? "border-accent-500/40 bg-accent-400/5"
          : "border-ink-800 hover:border-ink-700"
      }`}
    >
      <button
        type="button"
        onClick={() => setOpen((value) => !value)}
        aria-expanded={open}
        className="flex w-full items-center gap-3 p-4 text-left"
      >
        <span className="w-14 shrink-0 text-xs text-ink-400">{day}</span>
        <span className="min-w-0 flex-1">
          <span className="block truncate text-sm font-medium text-white">
            {row.description || row.paidTo || row.staffName || row.categoryName}
          </span>
          <span className="mt-0.5 block truncate text-xs text-ink-400">
            {row.categoryName}
            {row.staffName ? ` · ${row.staffName}` : row.paidTo ? ` · ${row.paidTo}` : ""}
            {row.autoGenerated ? " · auto" : ""}
          </span>
        </span>
        <span className="shrink-0 text-right">
          <span className="block text-sm font-semibold text-white">
            {formatCents(row.amountCents, currency)}
          </span>
          {row.taxPaidCents > 0 && (
            <span className="block text-xs text-ink-400">
              incl. {formatCents(row.taxPaidCents, currency)} {taxLabel}
            </span>
          )}
        </span>
        <span className="shrink-0 text-ink-500" aria-hidden>
          {open ? "▴" : "▾"}
        </span>
      </button>

      {open && (
        <div className="border-t border-ink-800 p-4">
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            <label className={label}>
              Date
              <input
                type="date"
                value={form.expenseDate}
                onChange={(event) => set("expenseDate", event.target.value)}
                className={`${input} mt-1`}
              />
            </label>
            <label className={label}>
              Category
              <select
                value={form.categoryId}
                onChange={(event) => set("categoryId", event.target.value)}
                className={`${input} mt-1`}
              >
                {categories.map((item) => (
                  <option key={item.id} value={item.id}>
                    {item.name}
                  </option>
                ))}
              </select>
            </label>
            {category?.isPayroll ? (
              <label className={label}>
                Who was paid?
                <select
                  value={form.staffUserId}
                  onChange={(event) => set("staffUserId", event.target.value)}
                  className={`${input} mt-1`}
                >
                  <option value="">Select a staff member…</option>
                  {staff.map((member) => (
                    <option key={member.id} value={member.id}>
                      {member.name}
                    </option>
                  ))}
                </select>
              </label>
            ) : (
              <label className={label}>
                Paid to
                <input
                  value={form.paidTo}
                  onChange={(event) => set("paidTo", event.target.value)}
                  className={`${input} mt-1`}
                />
              </label>
            )}
            <AmountFields
              amount={form.amount}
              taxPaid={form.taxPaid}
              onAmount={(value) => set("amount", value)}
              onTaxPaid={(value) => set("taxPaid", value)}
              taxRateBp={taxRateBp}
              taxLabel={taxLabel}
            />
            <label className={label}>
              Paid by
              <select
                value={form.paidBy}
                onChange={(event) => set("paidBy", event.target.value as ExpensePaymentMethod)}
                className={`${input} mt-1`}
              >
                {EXPENSE_PAYMENT_METHODS.map((method) => (
                  <option key={method} value={method}>
                    {EXPENSE_PAYMENT_METHOD_LABELS[method]}
                  </option>
                ))}
              </select>
            </label>
            <label className={label}>
              What was it for
              <input
                value={form.description}
                onChange={(event) => set("description", event.target.value)}
                className={`${input} mt-1`}
              />
            </label>
            <label className={label}>
              Invoice / cheque number
              <input
                value={form.reference}
                onChange={(event) => set("reference", event.target.value)}
                className={`${input} mt-1`}
              />
            </label>
          </div>

          {error && <p className="mt-3 text-sm text-red-400">{error}</p>}

          <div className="mt-4 flex flex-wrap items-center gap-2">
            <button
              type="button"
              onClick={() => void save()}
              disabled={busy}
              className="rounded-lg bg-accent-400 px-4 py-2 text-sm font-semibold text-ink-950 hover:bg-accent-300 disabled:opacity-40"
            >
              {busy ? "Saving…" : "Save changes"}
            </button>
            <button
              type="button"
              onClick={() => setOpen(false)}
              className="rounded-lg border border-ink-600 px-4 py-2 text-sm text-ink-200 hover:border-ink-500"
            >
              Cancel
            </button>
            <span className="flex-1" />
            {confirmingDelete ? (
              <>
                <span className="text-xs text-ink-300">Delete this permanently?</span>
                <button
                  type="button"
                  onClick={() => void remove()}
                  disabled={busy}
                  className="rounded-lg bg-red-500 px-4 py-2 text-sm font-semibold text-white hover:bg-red-400 disabled:opacity-40"
                >
                  Yes, delete
                </button>
                <button
                  type="button"
                  onClick={() => setConfirmingDelete(false)}
                  className="rounded-lg border border-ink-600 px-3 py-2 text-sm text-ink-200"
                >
                  Keep
                </button>
              </>
            ) : (
              <button
                type="button"
                onClick={() => setConfirmingDelete(true)}
                className="rounded-lg border border-red-900 px-4 py-2 text-sm text-red-300 hover:bg-red-950/30"
              >
                Delete
              </button>
            )}
          </div>
        </div>
      )}
    </article>
  );
}
