"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import {
  FinanceMetric,
  FinanceWorkspaceHeader,
  financeButton,
  financeInput,
  financeLabel,
  financePrimaryButton,
} from "@/components/finance-workspace";
import { PeriodNav } from "@/components/period-nav";
import { formatCents } from "@/lib/money";
import {
  EXPENSE_PAYMENT_METHODS,
  EXPENSE_PAYMENT_METHOD_LABELS,
  type ExpensePaymentMethod,
} from "@/lib/types";
import {
  confirmBillsAction,
  createExpenseAction,
  deleteExpenseAction,
  updateExpenseAction,
} from "./actions";
import { ExpenseReceipts, ReceiptPicker, uploadStagedReceipts } from "./receipt-upload";
import type { ExpenseReceipt } from "./receipts";

type Category = { id: string; name: string; isPayroll: boolean; active: boolean };
type StaffOption = { id: string; name: string; active: boolean };
type CategoryTotal = { categoryId: string; name: string; amountCents: number; count: number };

type ExpenseRow = {
  id: string;
  expenseDate: string;
  categoryId: string;
  categoryName: string;
  paidTo: string | null;
  staffUserId: string | null;
  staffName: string | null;
  description: string | null;
  amountCents: number;
  taxPaidCents: number;
  paidBy: string;
  reference: string | null;
  autoGenerated: boolean;
  confirmedAt: string | null;
  notes: string | null;
  receipts: ExpenseReceipt[];
};

type PeriodInfo = { kind: "month" | "quarter" | "year"; year: number; index: number; label: string };

const input = financeInput;
const label = financeLabel;
const card =
  "rounded-2xl border border-[#DCE4EC] bg-white p-5 shadow-[0_8px_24px_rgba(11,42,74,0.04)] sm:p-6";

function toCents(dollars: string): number {
  const value = Number(dollars);
  return Number.isFinite(value) ? Math.round(value * 100) : 0;
}
const toDollars = (cents: number) => (cents / 100).toFixed(2);

/** Blank form state, with today's date and the first selectable category. */
function emptyForm(today: string, categories: Category[]) {
  return {
    expenseDate: today,
    categoryId: categories.find((category) => category.active)?.id ?? "",
    paidTo: "",
    staffUserId: "",
    description: "",
    amount: "",
    taxPaid: "",
    paidBy: "other" as ExpensePaymentMethod,
    reference: "",
    notes: "",
  };
}
type FormState = ReturnType<typeof emptyForm>;

export function ExpenseManager({
  period,
  today,
  currency,
  taxRateBp,
  taxLabel,
  timezone,
  categories,
  staff,
  summary,
  expenses,
}: {
  period: PeriodInfo;
  today: string;
  currency: string;
  taxRateBp: number;
  taxLabel: string;
  timezone: string;
  categories: Category[];
  staff: StaffOption[];
  summary: {
    totalCents: number;
    inputTaxCreditCents: number;
    count: number;
    byCategory: CategoryTotal[];
  };
  expenses: ExpenseRow[];
}) {
  const router = useRouter();
  const money = (cents: number) => formatCents(cents, currency);
  const unconfirmed = expenses.filter((row) => row.autoGenerated && !row.confirmedAt);
  const [query, setQuery] = useState("");
  const [categoryFilter, setCategoryFilter] = useState("all");

  const visibleExpenses = useMemo(() => {
    const needle = query.trim().toLocaleLowerCase();
    return expenses.filter((row) => {
      if (categoryFilter !== "all" && row.categoryId !== categoryFilter) return false;
      if (!needle) return true;
      return [
        row.description,
        row.paidTo,
        row.staffName,
        row.categoryName,
        row.reference,
      ].some((value) => value?.toLocaleLowerCase().includes(needle));
    });
  }, [categoryFilter, expenses, query]);

  const largest = Math.max(1, ...summary.byCategory.map((entry) => entry.amountCents));

  return (
    <div className="max-w-[88rem]">
      <FinanceWorkspaceHeader
        active="expenses"
        title="Business expenses"
        description={`Record what the business paid, keep recurring bills in check, and capture the ${taxLabel} inside eligible purchases. Dates follow ${timezone}.`}
        actions={
          <a href="#add-expense" className={financePrimaryButton}>
            Add expense
          </a>
        }
      />

      <div className="mt-6 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-[#DCE4EC] bg-white p-4 shadow-[0_8px_24px_rgba(11,42,74,0.04)]">
        <PeriodNav period={period} basePath="/admin/expenses" />
        <a
          href={`/api/reports/export?kind=expenses&kindPeriod=${period.kind}&y=${period.year}&i=${period.index}`}
          className={financeButton}
        >
          Export CSV
        </a>
      </div>

      {/* Headline numbers */}
      <div className="mt-4 grid gap-4 sm:grid-cols-3">
        <FinanceMetric
          label="Total spent"
          value={money(summary.totalCents)}
          detail={period.label}
          tone="accent"
        />
        <FinanceMetric
          label={`${taxLabel} paid on purchases`}
          value={money(summary.inputTaxCreditCents)}
          detail="Available as input tax credits"
          tone="positive"
        />
        <FinanceMetric
          label="Payments recorded"
          value={summary.count}
          detail={unconfirmed.length > 0 ? `${unconfirmed.length} still need review` : "Everything is confirmed"}
          tone={unconfirmed.length > 0 ? "warning" : "default"}
        />
      </div>

      {unconfirmed.length > 0 && (
        <BillsToConfirm rows={unconfirmed} money={money} onDone={() => router.refresh()} />
      )}

      <AddExpense
        today={today}
        categories={categories}
        staff={staff}
        taxRateBp={taxRateBp}
        taxLabel={taxLabel}
        currency={currency}
      />

      {/* Where the money went */}
      {summary.byCategory.length > 0 && (
        <section className="mt-6 rounded-2xl border border-[#DCE4EC] bg-white p-5 shadow-[0_8px_24px_rgba(11,42,74,0.04)] sm:p-6">
          <div className="flex flex-wrap items-end justify-between gap-2">
            <div>
              <h2 className="text-base font-bold text-[#0B2A4A]">Spending by category</h2>
              <p className="mt-1 text-xs text-[#6B7D90]">Largest categories first for {period.label}.</p>
            </div>
            <p className="text-xs font-semibold text-[#718296]">{summary.byCategory.length} categories</p>
          </div>
          <div className="mt-5 space-y-3">
            {summary.byCategory.map((entry) => (
              <div key={entry.categoryId} className="grid grid-cols-[minmax(7rem,10rem)_1fr_auto] items-center gap-3">
                <span className="truncate text-sm font-medium text-[#344E65]">{entry.name}</span>
                <div className="h-2.5 overflow-hidden rounded-full bg-[#E8EDF2]">
                  <div
                    className="h-full rounded-full bg-[#E0A93B]"
                    style={{ width: `${Math.max(2, (entry.amountCents / largest) * 100)}%` }}
                  />
                </div>
                <span className="shrink-0 text-right">
                  <span className="block text-sm font-semibold text-[#0B2A4A]">{money(entry.amountCents)}</span>
                  <span className="block text-[10px] text-[#81909F]">{entry.count} {entry.count === 1 ? "payment" : "payments"}</span>
                </span>
              </div>
            ))}
          </div>
        </section>
      )}

      {/* Ledger */}
      <section className="mt-6 rounded-2xl border border-[#DCE4EC] bg-white p-5 shadow-[0_8px_24px_rgba(11,42,74,0.04)] sm:p-6">
        <div className="flex flex-wrap items-end justify-between gap-3">
          <div>
            <h2 className="text-base font-bold text-[#0B2A4A]">Expense ledger</h2>
            <p className="mt-1 text-xs text-[#6B7D90]">
              {visibleExpenses.length === expenses.length
                ? `${expenses.length} payments in ${period.label}`
                : `${visibleExpenses.length} of ${expenses.length} payments shown`}
            </p>
          </div>
          {expenses.length > 0 && (
            <div className="grid w-full gap-2 sm:w-auto sm:grid-cols-[15rem_11rem]">
              <label className="sr-only" htmlFor="expense-search">Search expenses</label>
              <input
                id="expense-search"
                type="search"
                value={query}
                onChange={(event) => setQuery(event.target.value)}
                placeholder="Search vendor, note or reference"
                className={financeInput}
              />
              <label className="sr-only" htmlFor="expense-category-filter">Filter by category</label>
              <select
                id="expense-category-filter"
                value={categoryFilter}
                onChange={(event) => setCategoryFilter(event.target.value)}
                className={financeInput}
              >
                <option value="all">All categories</option>
                {summary.byCategory.map((entry) => (
                  <option key={entry.categoryId} value={entry.categoryId}>{entry.name}</option>
                ))}
              </select>
            </div>
          )}
        </div>
        {expenses.length === 0 ? (
          <p className="mt-3 rounded-xl border border-dashed border-ink-700 p-8 text-center text-sm text-ink-400">
            Nothing recorded for {period.label} yet. Add your first expense above.
          </p>
        ) : (
          <div className="mt-5 space-y-2">
            {visibleExpenses.map((row) => (
              <ExpenseListRow
                key={row.id}
                row={row}
                categories={categories}
                staff={staff}
                currency={currency}
                taxRateBp={taxRateBp}
                taxLabel={taxLabel}
              />
            ))}
            {visibleExpenses.length === 0 && (
              <p className="rounded-xl bg-[#F6F8FA] px-4 py-8 text-center text-sm text-[#687B8E]">
                No expenses match those filters.
              </p>
            )}
          </div>
        )}
      </section>
    </div>
  );
}

/** Generated bills the owner has not ticked off yet. */
function BillsToConfirm({
  rows,
  money,
  onDone,
}: {
  rows: ExpenseRow[];
  money: (cents: number) => string;
  onDone: () => void;
}) {
  const [busy, setBusy] = useState(false);

  async function confirmAll() {
    setBusy(true);
    await confirmBillsAction({ expenseIds: rows.map((row) => row.id) });
    setBusy(false);
    onDone();
  }

  return (
    <section className="mt-6 rounded-2xl border border-[#E7C878] bg-[#FFF9E9] p-5 shadow-[0_8px_24px_rgba(122,84,14,0.06)]">
      <h2 className="text-sm font-bold text-[#735514]">
        {rows.length} monthly {rows.length === 1 ? "bill" : "bills"} to confirm
      </h2>
      <p className="mt-1 text-xs leading-5 text-[#765F2C]">
        These were created automatically from your recurring bills. Check the amount — open one to
        correct it (hydro varies) or delete it if it did not arrive this month.
      </p>
      <ul className="mt-3 divide-y divide-[#EEDDAF] rounded-xl border border-[#EAD394] bg-white/65 px-3 text-sm text-[#3F5367]">
        {rows.map((row) => (
          <li key={row.id} className="flex justify-between gap-4 py-2.5">
            <span className="truncate">{row.description ?? row.categoryName}</span>
            <span className="shrink-0 font-semibold text-[#0B2A4A]">{money(row.amountCents)}</span>
          </li>
        ))}
      </ul>
      <button
        type="button"
        onClick={() => void confirmAll()}
        disabled={busy}
        className="mt-4 inline-flex min-h-10 items-center justify-center rounded-xl bg-[#0B2A4A] px-4 py-2 text-sm font-semibold text-[#FFFFFF] hover:bg-[#123B63] disabled:opacity-40"
      >
        {busy ? "Confirming…" : "These are all correct"}
      </button>
    </section>
  );
}

/** Shared amount + tax pair, with the HST back-out button. */
function AmountFields({
  amount,
  taxPaid,
  onAmount,
  onTaxPaid,
  taxRateBp,
  taxLabel,
}: {
  amount: string;
  taxPaid: string;
  onAmount: (value: string) => void;
  onTaxPaid: (value: string) => void;
  taxRateBp: number;
  taxLabel: string;
}) {
  // Mirrors taxIncludedInCents in src/lib/books.ts: the tax inside a
  // tax-inclusive total, not the tax added on top of it.
  const included = useMemo(() => {
    const cents = toCents(amount);
    if (cents <= 0 || taxRateBp <= 0) return 0;
    return Math.round((cents * taxRateBp) / (10_000 + taxRateBp));
  }, [amount, taxRateBp]);

  return (
    <>
      <label className={label}>
        Amount paid
        <input
          type="number"
          step="0.01"
          min="0"
          inputMode="decimal"
          placeholder="0.00"
          value={amount}
          onChange={(event) => onAmount(event.target.value)}
          className={`${input} mt-1`}
        />
      </label>
      <label className={label}>
        {taxLabel} within that amount
        <input
          type="number"
          step="0.01"
          min="0"
          inputMode="decimal"
          placeholder="0.00"
          value={taxPaid}
          onChange={(event) => onTaxPaid(event.target.value)}
          className={`${input} mt-1`}
        />
        {included > 0 && (
          <button
            type="button"
            onClick={() => onTaxPaid(toDollars(included))}
            className="mt-1.5 text-xs font-semibold text-[#805D16] underline underline-offset-2 hover:text-[#5F4510]"
          >
            Receipt includes {taxLabel}? Use {(included / 100).toFixed(2)}
          </button>
        )}
      </label>
    </>
  );
}

function AddExpense({
  today,
  categories,
  staff,
  taxRateBp,
  taxLabel,
  currency,
}: {
  today: string;
  categories: Category[];
  staff: StaffOption[];
  taxRateBp: number;
  taxLabel: string;
  currency: string;
}) {
  const router = useRouter();
  const [form, setForm] = useState<FormState>(() => emptyForm(today, categories));
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [saved, setSaved] = useState(false);
  const [showOptional, setShowOptional] = useState(false);
  // Held in the browser until the expense row exists to hang them off.
  const [receiptFiles, setReceiptFiles] = useState<File[]>([]);

  const category = categories.find((item) => item.id === form.categoryId);
  const set = <K extends keyof FormState>(key: K, value: FormState[K]) =>
    setForm((current) => ({ ...current, [key]: value }));

  async function save() {
    setBusy(true);
    setError(null);
    setSaved(false);
    const result = await createExpenseAction({
      expenseDate: form.expenseDate,
      categoryId: form.categoryId,
      paidTo: form.paidTo,
      staffUserId: form.staffUserId || null,
      description: form.description,
      amountCents: toCents(form.amount),
      taxPaidCents: toCents(form.taxPaid),
      paidBy: form.paidBy,
      reference: form.reference,
      notes: form.notes,
    });
    if (!result.ok) {
      setBusy(false);
      setError(result.error);
      return;
    }
    // The expense is saved by this point, so a failed upload is reported and
    // the files are kept staged for a retry — never a reason to lose the row.
    const uploadError = await uploadStagedReceipts(result.expenseId, receiptFiles);
    setBusy(false);
    if (uploadError) {
      setError(`Expense saved, but the receipt did not upload: ${uploadError}`);
      return;
    }
    setReceiptFiles([]);
    // Keep the date and category — expenses are entered in batches from a pile
    // of receipts, and re-picking the same category every time is the friction
    // that sends people back to the spreadsheet.
    setForm((current) => ({
      ...emptyForm(today, categories),
      expenseDate: current.expenseDate,
      categoryId: current.categoryId,
      paidBy: current.paidBy,
    }));
    setSaved(true);
    router.refresh();
  }

  return (
    <section id="add-expense" className={`mt-6 scroll-mt-24 ${card}`}>
      <div>
        <h2 className="text-base font-bold text-[#0B2A4A]">Add an expense</h2>
        <p className="mt-1 text-xs leading-5 text-[#6B7D90]">
          Start with the receipt essentials. The date, category and payment method stay selected
          after saving so a stack of receipts is faster to enter.
        </p>
      </div>
      <div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        <label className={label}>
          Date
          <input
            type="date"
            value={form.expenseDate}
            onChange={(event) => set("expenseDate", event.target.value)}
            className={`${input} mt-1`}
          />
        </label>
        <label className={label}>
          Category
          <select
            value={form.categoryId}
            onChange={(event) => set("categoryId", event.target.value)}
            className={`${input} mt-1`}
          >
            {categories
              .filter((item) => item.active || item.id === form.categoryId)
              .map((item) => (
                <option key={item.id} value={item.id}>
                  {item.name}
                  {item.active ? "" : " (inactive)"}
                </option>
              ))}
          </select>
        </label>
        {category?.isPayroll ? (
          <label className={label}>
            Who was paid?
            <select
              value={form.staffUserId}
              onChange={(event) => set("staffUserId", event.target.value)}
              className={`${input} mt-1`}
            >
              <option value="">Select a staff member…</option>
              {staff
                .filter((member) => member.active)
                .map((member) => (
                  <option key={member.id} value={member.id}>
                    {member.name}
                  </option>
                ))}
            </select>
          </label>
        ) : (
          <label className={label}>
            Paid to
            <input
              value={form.paidTo}
              onChange={(event) => set("paidTo", event.target.value)}
              placeholder="Supplier or vendor"
              className={`${input} mt-1`}
            />
          </label>
        )}
        <AmountFields
          amount={form.amount}
          taxPaid={form.taxPaid}
          onAmount={(value) => set("amount", value)}
          onTaxPaid={(value) => set("taxPaid", value)}
          taxRateBp={taxRateBp}
          taxLabel={taxLabel}
        />
        <label className={label}>
          Paid by
          <select
            value={form.paidBy}
            onChange={(event) => set("paidBy", event.target.value as ExpensePaymentMethod)}
            className={`${input} mt-1`}
          >
            {EXPENSE_PAYMENT_METHODS.map((method) => (
              <option key={method} value={method}>
                {EXPENSE_PAYMENT_METHOD_LABELS[method]}
              </option>
            ))}
          </select>
        </label>
      </div>

      <div className="mt-4 rounded-xl border border-[#E0E6EC] bg-[#F8FAFC]">
        <button
          type="button"
          onClick={() => setShowOptional((current) => !current)}
          aria-expanded={showOptional}
          className="flex min-h-11 w-full items-center justify-between gap-3 px-4 py-2 text-left text-xs font-semibold text-[#526A80]"
        >
          Description, reference and notes
          <span aria-hidden="true" className="text-[#7E8D9C]">{showOptional ? "−" : "+"}</span>
        </button>
        {showOptional && (
          <div className="grid gap-4 border-t border-[#E0E6EC] p-4 sm:grid-cols-2">
            <label className={label}>
              What was it for
              <input
                value={form.description}
                onChange={(event) => set("description", event.target.value)}
                placeholder="Optional description"
                className={`${input} mt-1`}
              />
            </label>
            <label className={label}>
              Invoice / cheque number
              <input
                value={form.reference}
                onChange={(event) => set("reference", event.target.value)}
                placeholder="Optional reference"
                className={`${input} mt-1`}
              />
            </label>
            <label className={`${label} sm:col-span-2`}>
              Internal notes
              <textarea
                value={form.notes}
                onChange={(event) => set("notes", event.target.value)}
                rows={2}
                placeholder="Optional context for the owner or accountant"
                className={`${input} mt-1`}
              />
            </label>
          </div>
        )}
      </div>

      <ReceiptPicker files={receiptFiles} onChange={setReceiptFiles} />

      {error && <p className="mt-3 text-sm text-red-400">{error}</p>}
      {saved && <p className="mt-3 text-sm text-emerald-300">Expense saved.</p>}

      <div className="mt-4 flex flex-wrap items-center gap-3">
        <button
          type="button"
          onClick={() => void save()}
          disabled={busy}
          className={financePrimaryButton}
        >
          {busy ? "Saving…" : "Save expense"}
        </button>
        {toCents(form.amount) > 0 && (
          <span className="text-sm text-ink-400">
            Recording {formatCents(toCents(form.amount), currency)}
          </span>
        )}
      </div>
    </section>
  );
}

function ExpenseListRow({
  row,
  categories,
  staff,
  currency,
  taxRateBp,
  taxLabel,
}: {
  row: ExpenseRow;
  categories: Category[];
  staff: StaffOption[];
  currency: string;
  taxRateBp: number;
  taxLabel: string;
}) {
  const router = useRouter();
  const [open, setOpen] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [confirmingDelete, setConfirmingDelete] = useState(false);
  const [form, setForm] = useState({
    expenseDate: row.expenseDate.slice(0, 10),
    categoryId: row.categoryId,
    paidTo: row.paidTo ?? "",
    staffUserId: row.staffUserId ?? "",
    description: row.description ?? "",
    amount: toDollars(row.amountCents),
    taxPaid: toDollars(row.taxPaidCents),
    paidBy: row.paidBy as ExpensePaymentMethod,
    reference: row.reference ?? "",
    notes: row.notes ?? "",
  });

  const category = categories.find((item) => item.id === form.categoryId);
  const set = <K extends keyof typeof form>(key: K, value: (typeof form)[K]) =>
    setForm((current) => ({ ...current, [key]: value }));

  async function save() {
    setBusy(true);
    setError(null);
    const result = await updateExpenseAction({
      expenseId: row.id,
      expenseDate: form.expenseDate,
      categoryId: form.categoryId,
      paidTo: form.paidTo,
      staffUserId: form.staffUserId || null,
      description: form.description,
      amountCents: toCents(form.amount),
      taxPaidCents: toCents(form.taxPaid),
      paidBy: form.paidBy,
      reference: form.reference,
      notes: form.notes,
    });
    setBusy(false);
    if (!result.ok) return setError(result.error);
    setOpen(false);
    router.refresh();
  }

  async function remove() {
    setBusy(true);
    setError(null);
    const result = await deleteExpenseAction({ expenseId: row.id });
    setBusy(false);
    if (!result.ok) return setError(result.error);
    router.refresh();
  }

  const day = new Date(row.expenseDate).toLocaleDateString("en-CA", {
    month: "short",
    day: "numeric",
  });

  return (
    <article
      className={`overflow-hidden rounded-xl border transition-colors ${
        row.autoGenerated && !row.confirmedAt
          ? "border-[#E5C66D] bg-[#FFF9EA]"
          : "border-[#DFE6ED] bg-white hover:border-[#B9C7D4]"
      }`}
    >
      <button
        type="button"
        onClick={() => setOpen((value) => !value)}
        aria-expanded={open}
        className="flex min-h-16 w-full items-center gap-3 p-4 text-left outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-[#E0A93B]"
      >
        <span className="w-14 shrink-0 text-xs font-semibold text-[#718296]">{day}</span>
        <span className="min-w-0 flex-1">
          <span className="block truncate text-sm font-semibold text-[#0B2A4A]">
            {row.description || row.paidTo || row.staffName || row.categoryName}
          </span>
          <span className="mt-0.5 block truncate text-xs text-[#718296]">
            {row.categoryName}
            {row.staffName ? ` · ${row.staffName}` : row.paidTo ? ` · ${row.paidTo}` : ""}
            {row.autoGenerated ? " · auto" : ""}
            {/* Visible on the collapsed row so "which of these has paperwork?"
                is answerable without opening every one. */}
            {row.receipts.length > 0
              ? ` · ${row.receipts.length} ${row.receipts.length === 1 ? "receipt" : "receipts"}`
              : ""}
          </span>
        </span>
        <span className="shrink-0 text-right">
          <span className="block text-sm font-bold text-[#0B2A4A]">
            {formatCents(row.amountCents, currency)}
          </span>
          {row.taxPaidCents > 0 && (
            <span className="block text-xs text-[#718296]">
              incl. {formatCents(row.taxPaidCents, currency)} {taxLabel}
            </span>
          )}
        </span>
        <span className="shrink-0 text-[#7E8D9C]" aria-hidden>
          {open ? "▴" : "▾"}
        </span>
      </button>

      {open && (
        <div className="border-t border-[#E1E7ED] bg-[#F8FAFC] p-4">
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            <label className={label}>
              Date
              <input
                type="date"
                value={form.expenseDate}
                onChange={(event) => set("expenseDate", event.target.value)}
                className={`${input} mt-1`}
              />
            </label>
            <label className={label}>
              Category
              <select
                value={form.categoryId}
                onChange={(event) => set("categoryId", event.target.value)}
                className={`${input} mt-1`}
              >
                {categories.map((item) => (
                  <option key={item.id} value={item.id}>
                    {item.name}
                  </option>
                ))}
              </select>
            </label>
            {category?.isPayroll ? (
              <label className={label}>
                Who was paid?
                <select
                  value={form.staffUserId}
                  onChange={(event) => set("staffUserId", event.target.value)}
                  className={`${input} mt-1`}
                >
                  <option value="">Select a staff member…</option>
                  {staff
                    .filter((member) => member.active || member.id === form.staffUserId)
                    .map((member) => (
                      <option key={member.id} value={member.id}>
                        {member.name}
                        {member.active ? "" : " (no longer active)"}
                      </option>
                    ))}
                </select>
              </label>
            ) : (
              <label className={label}>
                Paid to
                <input
                  value={form.paidTo}
                  onChange={(event) => set("paidTo", event.target.value)}
                  className={`${input} mt-1`}
                />
              </label>
            )}
            <AmountFields
              amount={form.amount}
              taxPaid={form.taxPaid}
              onAmount={(value) => set("amount", value)}
              onTaxPaid={(value) => set("taxPaid", value)}
              taxRateBp={taxRateBp}
              taxLabel={taxLabel}
            />
            <label className={label}>
              Paid by
              <select
                value={form.paidBy}
                onChange={(event) => set("paidBy", event.target.value as ExpensePaymentMethod)}
                className={`${input} mt-1`}
              >
                {EXPENSE_PAYMENT_METHODS.map((method) => (
                  <option key={method} value={method}>
                    {EXPENSE_PAYMENT_METHOD_LABELS[method]}
                  </option>
                ))}
              </select>
            </label>
            <label className={label}>
              What was it for
              <input
                value={form.description}
                onChange={(event) => set("description", event.target.value)}
                className={`${input} mt-1`}
              />
            </label>
            <label className={label}>
              Invoice / cheque number
              <input
                value={form.reference}
                onChange={(event) => set("reference", event.target.value)}
                className={`${input} mt-1`}
              />
            </label>
            <label className={`${label} sm:col-span-2 lg:col-span-3`}>
              Internal notes
              <textarea
                value={form.notes}
                onChange={(event) => set("notes", event.target.value)}
                rows={2}
                className={`${input} mt-1`}
              />
            </label>
          </div>

          {/* Outside the field grid: receipts upload on drop, they are not part
              of the form the Save button submits. */}
          <div className="mt-4 border-t border-[#E1E7ED] pt-4">
            <ExpenseReceipts expenseId={row.id} receipts={row.receipts} />
          </div>

          {error && <p className="mt-3 text-sm text-red-400">{error}</p>}

          <div className="mt-4 flex flex-wrap items-center gap-2">
            <button
              type="button"
              onClick={() => void save()}
              disabled={busy}
              className="rounded-lg bg-accent-400 px-4 py-2 text-sm font-semibold text-ink-950 hover:bg-accent-300 disabled:opacity-40"
            >
              {busy ? "Saving…" : "Save changes"}
            </button>
            <button
              type="button"
              onClick={() => setOpen(false)}
              className="rounded-lg border border-ink-600 px-4 py-2 text-sm text-ink-200 hover:border-ink-500"
            >
              Cancel
            </button>
            <span className="flex-1" />
            {confirmingDelete ? (
              <>
                <span className="text-xs text-ink-300">Delete this permanently?</span>
                <button
                  type="button"
                  onClick={() => void remove()}
                  disabled={busy}
                  className="rounded-lg bg-red-500 px-4 py-2 text-sm font-semibold text-white hover:bg-red-400 disabled:opacity-40"
                >
                  Yes, delete
                </button>
                <button
                  type="button"
                  onClick={() => setConfirmingDelete(false)}
                  className="rounded-lg border border-ink-600 px-3 py-2 text-sm text-ink-200"
                >
                  Keep
                </button>
              </>
            ) : (
              <button
                type="button"
                onClick={() => setConfirmingDelete(true)}
                className="rounded-lg border border-red-900 px-4 py-2 text-sm text-red-300 hover:bg-red-950/30"
              >
                Delete
              </button>
            )}
          </div>
        </div>
      )}
    </article>
  );
}
